version: '1.0'

services:
  rdai_miniproj_aip:
    build: 
      context: ./
    image: rdai_miniproj_aip:v1.0
    container_name: rdai_miniproj_aip
    ports:
      - 8080:8080
    volumes:
      - ./:/workspace
    ulimits:
      memlock: -1 # set upper limit for how much memory is locked for the container (-1 means lock as much as the container uses)
    shm_size: 32gb # set upper limit for how much shared memory container can use
    ipc: "host"
    working_dir: /workspace
    command: ["uvicorn", "apiService:app", "--host", "0.0.0.0", "--port", "8080"]